### ISSUE TITLE
Autosave open session

### ISSUE THREAD

**Issue by orschiro** [onikienko/TabHamster#22]
Hi @onikienko,

Thanks for this great extension. TabHamster is the best session manager that I have found so far because of its simplicity!

One question that I cannot figure out myself. I have created three distinct sessions. What I usually do is to open a session and work on it, i.e. opening new tabs and deleting old ones. Thus, the status of my named session has changed. In order to save this new state, I first need to delete the current tab session to create a new one with exactly the same name. 

Have I overlooked an auto-save or save-under-same-name feature?

Thankfully,

Robert

**Comment by onikienko** [comment]
Hi @orschiro,

>or save-under-same-name feature?
Good point. Will try in next update.

Thank you for feedback.

**Comment by orschiro** [comment]
Thanks! I am glad my feedback was useful.

**Comment by orschiro** [comment]
Thanks for your update!

Lazy type mode on sent from mobile

**Comment by onikienko** [comment]
Thank you for feedback.
