### ISSUE TITLE
Unable to synchronize (Opera 28)

### ISSUE THREAD

**Issue by hurt09** [onikienko/TabHamster#23]
Hi!

What am I doing wrong when TabHamster does not synchronize? I am using Opera 28 at home and at work (with synchronization enabled of course) and can't get it to work :-/

Anyone else has this issue?

**Comment by hurt09** [comment]
Does nobody have the same issue? :-)

**Comment by onikienko** [comment]
Opera do not support chrome.storage.sync at the moment.   
So you can't sync your saved groups in Opera :pensive:   

Now i'm working on manual import\export feature.

**Comment by hurt09** [comment]
That would be a great feature indeed! :-)

**Comment by iandol** [comment]
@onikienko — did you ever get opera to sync or support import/export?

**Comment by hurt09** [comment]
I'm still interested in a export/import feature as well :-D

**Comment by onikienko** [comment]
I'm back. Will try to do this month

**Comment by hurt09** [comment]
YAY! :+1:

**Comment by onikienko** [comment]
@hurt09 @iandol
Manual Backup/Restore in v0.2.9 (to find this feature go to extension options page)
Will be available in marktet after moderation

**Comment by hurt09** [comment]
Works perfect - thanks a lot! :-D
