### ISSUE TITLE
Option to place TabHamster on Opera sidebar

### ISSUE THREAD

**Issue by Twilightssuperb** [onikienko/TabHamster#29]
Изложу пожелание по-русски. К сожалению, «Опера» до сих пор с момента переезда на Blink не позволяет перемещать иконки расширений по основной панели инструментов. И когда их установлено более 15, то самые поздние попросту не появляются на тулбаре. Лишь после того, как вручную отключаешь старые. 
Зато с 29-ой версии в браузер внедрили боковую панель для расширений, которая выглядит очень удобно и куда при необходимости тоже можно добавлять иконки. Это частично избавляет от беспокойства, как уместить два десятка расширений в окне браузера, и этим начали пользоваться разработчики некоторых других расширений (e.g., Raindrop, SimpleExtManager) ― предоставляя юзеру выбор, где будет находиться иконка. Впрочем, пока хорошего менеджера сессий для боковой панели лично я не нашел в каталоге адд-онов «Оперы», так что буду рад, если TabHamster пропишется там. :)

**Comment by onikienko** [comment]
Спасибо. Позже посмотрю обязательно.

**Comment by onikienko** [comment]
The extension does not support Opera anymore.
