### ISSUE TITLE
Where in my PC is my tabhamster bookmarks and session saved to locally?

### ISSUE THREAD

**Issue by collizo4sky** [onikienko/TabHamster#34]
Somebody answer please.

**Comment by onikienko** [comment]
TabHamster save groups in chrome.storage.sync and sessions in localStorage.

**Comment by collizo4sky** [comment]
I use opera. am guessing this local storage is a file system in my PC right? where can i locate it.

**Comment by onikienko** [comment]
Take a look on that http://stackoverflow.com/questions/9669184/how-is-html5-webstorage-data-physically-stored

But why you need it? I think it easiest to get you saved data via TabHamster -> Options -> Backup/Restore

**Comment by collizo4sky** [comment]
Oops. was looking for it because i wanted to backup.  Never knew it existed already.

Closing this now

**Comment by onikienko** [comment]
Please note! There is **no** ability in TabHamster to Backup/Restore sessions. Saved groups only.
