### ISSUE TITLE
Do not close interface upon clicking one link

### ISSUE THREAD

**Issue by HiPoEGH** [onikienko/TabHamster#49]
Please add the option to NOT close the interface upon clicking one link on a saved tab. 
Sometimes a user might want to open different links from a saved group, but not all the links. Having to open the interface again, and find the group name again, is **rather annoying**. 

**If someone wants to close the interface, let them do it themselves.**

**Comment by onikienko** [comment]
Chrome closes the extension's popup when you open a new tab. It's by Chrome design.
