### ISSUE TITLE
TabHamster Suddenly Disappeared

### ISSUE THREAD

**Issue by sohaali** [onikienko/TabHamster#6]
Thanks for this great extension for Opera.

Last night there was a power outage, and when I restarted the system, the extension had gone. Yes just like that... suddenly disappeared. 

I could always install again, but the problem is that there was a long list of important sites in the SAVED GROUPS for a research that I am doing.

Is there a way to get them back? (please treat this as urgent)

**Comment by onikienko** [comment]
The extension does not support Opera anymore.
